name: "Cloud Function Hosting Check"
description: "Ensure all exported functions also have a hosting config"
author: "Jackson Prowell"
inputs:
  index-path:
    description: "Path to your Firebase cloud function index.ts file"
    required: true
  firebase-config-path:
    description: "Path to your firebase.json file"
    required: true
  ignored-functions:
    description: "A space-separated list of function names to ignore discrepancies for"
    required: false
    default: ""
runs:
  using: "node20"
  main: "dist/index.js"
